// Supabase Database Types
// This file will be auto-generated by Supabase CLI in production
// For now, we define the types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          cnpj: string | null;
          sector: string | null;
          size: string | null;
          logo_url: string | null;
          plan: string;
          ai_usage_status: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          cnpj?: string | null;
          sector?: string | null;
          size?: string | null;
          logo_url?: string | null;
          plan?: string;
          ai_usage_status?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          cnpj?: string | null;
          sector?: string | null;
          size?: string | null;
          logo_url?: string | null;
          plan?: string;
          ai_usage_status?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          company_id: string | null;
          name: string;
          email: string;
          role: string;
          department: string | null;
          position: string | null;
          avatar_url: string | null;
          ai_level: number;
          onboarding_completed: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          company_id?: string | null;
          name: string;
          email: string;
          role?: string;
          department?: string | null;
          position?: string | null;
          avatar_url?: string | null;
          ai_level?: number;
          onboarding_completed?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string | null;
          name?: string;
          email?: string;
          role?: string;
          department?: string | null;
          position?: string | null;
          avatar_url?: string | null;
          ai_level?: number;
          onboarding_completed?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      courses: {
        Row: {
          id: string;
          slug: string;
          title: string;
          description: string | null;
          level: number;
          category: string | null;
          area: string;
          thumbnail_url: string | null;
          duration_minutes: number;
          modules_count: number;
          students_count: number;
          ai_tutor_enabled: boolean;
          ai_tutor_context: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          description?: string | null;
          level?: number;
          category?: string | null;
          area?: string;
          thumbnail_url?: string | null;
          duration_minutes?: number;
          modules_count?: number;
          students_count?: number;
          ai_tutor_enabled?: boolean;
          ai_tutor_context?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          description?: string | null;
          level?: number;
          category?: string | null;
          area?: string;
          thumbnail_url?: string | null;
          duration_minutes?: number;
          modules_count?: number;
          students_count?: number;
          ai_tutor_enabled?: boolean;
          ai_tutor_context?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      course_modules: {
        Row: {
          id: string;
          course_id: string;
          slug: string;
          title: string;
          description: string | null;
          content_type: string;
          content_url: string | null;
          video_transcript: string | null;
          ai_summary: string | null;
          exercise_prompt: string | null;
          duration_minutes: number;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          slug: string;
          title: string;
          description?: string | null;
          content_type?: string;
          content_url?: string | null;
          video_transcript?: string | null;
          ai_summary?: string | null;
          exercise_prompt?: string | null;
          duration_minutes?: number;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          slug?: string;
          title?: string;
          description?: string | null;
          content_type?: string;
          content_url?: string | null;
          video_transcript?: string | null;
          ai_summary?: string | null;
          exercise_prompt?: string | null;
          duration_minutes?: number;
          sort_order?: number;
          created_at?: string;
        };
      };
      user_course_progress: {
        Row: {
          id: string;
          user_id: string;
          course_id: string;
          current_module_id: string | null;
          progress_percent: number;
          started_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          course_id: string;
          current_module_id?: string | null;
          progress_percent?: number;
          started_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          course_id?: string;
          current_module_id?: string | null;
          progress_percent?: number;
          started_at?: string;
          completed_at?: string | null;
        };
      };
      user_module_progress: {
        Row: {
          id: string;
          user_id: string;
          module_id: string;
          status: string;
          score: number | null;
          time_spent_minutes: number;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          module_id: string;
          status?: string;
          score?: number | null;
          time_spent_minutes?: number;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          module_id?: string;
          status?: string;
          score?: number | null;
          time_spent_minutes?: number;
          completed_at?: string | null;
        };
      };
      certificates: {
        Row: {
          id: string;
          user_id: string;
          course_id: string;
          certificate_number: string;
          issued_at: string;
          pdf_url: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          course_id: string;
          certificate_number: string;
          issued_at?: string;
          pdf_url?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          course_id?: string;
          certificate_number?: string;
          issued_at?: string;
          pdf_url?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
